SELECT ITEM_REF1, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF1 IS NOT NULL AND ITEM_REF1 <> '' UNION ALL
SELECT ITEM_REF2, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF2 IS NOT NULL AND ITEM_REF2 <> '' UNION ALL
SELECT ITEM_REF3, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF3 IS NOT NULL AND ITEM_REF3 <> '' UNION ALL
SELECT ITEM_REF4, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF4 IS NOT NULL AND ITEM_REF4 <> '' UNION ALL
SELECT ITEM_REF5, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF5 IS NOT NULL AND ITEM_REF5 <> '' UNION ALL
SELECT ITEM_REF6, ITEM_CODE FROM AAA_BARCORD_LIVE WHERE ITEM_REF6 IS NOT NULL AND ITEM_REF6 <> '';
