curl.exe -O "https://fossil-scm.org/home/uv/fossil-w64-2.23.zip"
Expand-Archive "./fossil-w64-2.23.zip"
copy fossil.exe "c:\windows\"
curl.exe -O "https://curl.se/ca/cacert.pem"
copy cacert.pem "c:\windows\"
